apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-web
  labels:
    app: blog-web
spec:
  selector:
    matchLabels:
      app: blog-web
  template:
    metadata:
      labels:
        app: blog-web
    spec:
      containers:
      - name: blog-web
        image: hw038/blog-web
        env:
        - name: DB_HOST
          value: mysql-service.default.svc.cluster.local
        - name: DB_NAME
          value: blog
        - name: DB_USER
          value: root
        - name: DB_PWD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: password
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: blog-web
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: blog-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
  labels:
    app: mysql-server
spec:
  selector:
    matchLabels:
      app: mysql-server
  template:
    metadata:
      labels:
        app: mysql-server
    spec:
      containers:
      - name: mysql-server
        image: hw038/blog-mysql
        env:
        - name: MYSQL_DATABASE
          value: blog
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: db-azurefile
---
kind: Service
apiVersion: v1
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql-server
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
